In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

In [6]:
fakedata = np.tile(np.array([1,2,3,4]),(10,1)) + np.tile(10*np.arange(1,11),(4,1)).T
fakelabels = np.arange(10)>4
print(fakedata), print(' ')
print(fakelabels)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]
 
[False False False False False  True  True  True  True  True]


In [14]:
proportions = [.8, .1, .1]
train_data, test_tmp_data, train_labels, test_tmp_labels = \
            train_test_split(fakedata, fakelabels, train_size=proportions[0])

split = proportions[1] / np.sum(proportions[1:])
devset_data, test_data, devset_labels, test_labels = \
            train_test_split(test_tmp_data, test_tmp_labels, train_size=split) 


print(f"Training data size: {train_data.shape}")
print(f"Devset data size: {devset_data.shape}")
print(f"Test data size: {test_data.shape}")
print(" ")

print("Training data: ")
print(train_data)
print(' ')

print("Devset data: ")
print(devset_data)
print(' ')

print("Test data: ")
print(test_data)
print(' ')

Training data size: (8, 4)
Devset data size: (1, 4)
Test data size: (1, 4)
 
Training data: 
[[ 11  12  13  14]
 [ 41  42  43  44]
 [ 31  32  33  34]
 [ 51  52  53  54]
 [ 91  92  93  94]
 [ 21  22  23  24]
 [101 102 103 104]
 [ 81  82  83  84]]
 
Devset data: 
[[61 62 63 64]]
 
Test data: 
[[71 72 73 74]]
 


In [17]:
# Split with numpy
partitions = np.array([.8, .1, .1])
print('Partition proportions')
print(partitions)
print(' ')

partition_bnd = np.cumsum(partitions*len(fakelabels)).astype(int)
print("Partitioin boundaries:")
print(partition_bnd)
print(' ')

randindices = np.random.permutation(range(len(fakelabels)))
print("Randomized data indices:")
print(randindices)
print(' ')

Partition proportions
[0.8 0.1 0.1]
 
Partitioin boundaries:
[ 8  9 10]
 
Randomized data indices:
[3 0 7 9 5 4 1 2 8 6]
 


In [21]:
train_dataN = fakedata[randindices[:partition_bnd[0]],:]
train_labelsN = fakelabels[randindices[:partition_bnd[0]]]

devset_dataN = fakedata[randindices[partition_bnd[0]:partition_bnd[1]],:]
devset_labelsN = fakelabels[randindices[partition_bnd[0]:partition_bnd[1]]]

test_dataN = fakedata[randindices[partition_bnd[1]:],:]
test_labelsN = fakelabels[randindices[partition_bnd[1]:]]

In [22]:

print(f"Training data size: {train_dataN.shape}")
print(f"Devset data size: {devset_dataN.shape}")
print(f"Test data size: {test_dataN.shape}")
print(" ")

print("Training data: ")
print(train_dataN)
print(' ')

print("Devset data: ")
print(devset_dataN)
print(' ')

print("Test data: ")
print(test_dataN)
print(' ')

Training data size: (8, 4)
Devset data size: (1, 4)
Test data size: (1, 4)
 
Training data: 
[[ 41  42  43  44]
 [ 11  12  13  14]
 [ 81  82  83  84]
 [101 102 103 104]
 [ 61  62  63  64]
 [ 51  52  53  54]
 [ 21  22  23  24]
 [ 31  32  33  34]]
 
Devset data: 
[[91 92 93 94]]
 
Test data: 
[[71 72 73 74]]
 
